### PR TITLE
Update PR template

### PR DESCRIPTION
**Pull request by bonniegee**
Focuses on discussion questions per the suggestions in the sprint retrospective.

Is this useful? Should headings be reworded, removed, or added?

### CODE REVIEW

**Comment by p-galligan** [comment]
What's the description section? Just a short description of the changes involved in the PR?

**Comment by bonniegee** [comment]
Yep--does it make sense to change that to "Changes"?

**Comment by bonniegee** [comment]
Another possibility is to include helper text for each heading. Would that be useful?

**Comment by p-galligan** [comment]
Yeah, I'd argue for Key Changes or something like that. Otherwise it just looks like a re-iteration of the issue.

**Comment by helrond** [comment]
Helper text is a great idea!

**Comment by p-galligan** [comment]
Yeah, helper text would fix any confusion.

**Comment by bonniegee** [comment]
@helrond @p-galligan -- Changed the heading and added helper text. Would anything else be useful?

**Review by helrond — APPROVED** [review]

**Review by p-galligan — APPROVED** [review]

**Review by HaSistrunk — APPROVED** [review]
Looks good! Thanks @bonniegee

**Pull request merged**
