### PR TITLE
WIP: unit tests for data helpers

### LINKED ISSUE #34: Add unit tests for data helpers that do not require data from ArchivesSpace
**Is your feature request related to a problem? Please describe.**
In order to know that our code is working (and remains working as we update it) we should have unit tests in place which assert expected outputs given prescribed inputs.

**Describe the solution you'd like**
Unit tests for all of the functions in `data_helpers.py`

### PR DESCRIPTION
**Pull request by p-galligan**
## Proposed Changes

  - Need to actually include ways to get data into the functions from AS
  - Only two tests here, we need more coverage, just didn't get time.

### CODE REVIEW

**Review by helrond — COMMENTED** [review]
This is a really excellent start!

We definitely want to have some more robust mocking mechanism to ensure we test the right things with these functions.

**Comment by helrond** [comment]
Would suggest removing the `fixes` from this issue as well, since as you note there's more work to be done here...

**Comment by p-galligan** [comment]
@helrond this is throwing an error on `TypeException` should that be `TypeError` instead?

**Review by helrond — APPROVED** [review]
This should pass once #45 is merged.

**Review by HaSistrunk — APPROVED** [review]

**Pull request merged**
