### PR TITLE
WIP: Issue 34 Add Unit Tests to Data Helpers that don't require connecting to AS

### LINKED ISSUE #34: Add unit tests for data helpers that do not require data from ArchivesSpace
**Is your feature request related to a problem? Please describe.**
In order to know that our code is working (and remains working as we update it) we should have unit tests in place which assert expected outputs given prescribed inputs.

**Describe the solution you'd like**
Unit tests for all of the functions in `data_helpers.py`

### PR DESCRIPTION
**Pull request by p-galligan**
Fixes #34 by adding tests for data helpers that don't require connecting to AS

## Changes
Adding tests for functions in data helpers.

### CODE REVIEW

**Comment by p-galligan** [comment]
So it looks like tests are failing due to having a dictionary instead of an object. Not exactly sure what to do about that for this PR.

Where `getattr` won't work on a dictionary.

**Comment by helrond** [comment]
If you have time, I think fixing the data helpers functions is a good idea...

**Comment by p-galligan** [comment]
Do you mean “fix” them to use dict.get instead of getattr? Or were you thinking something else?

**Comment by helrond** [comment]
Well, if you're confident that your unit test is testing the right thing, then if the test fails there's something wrong with the function being tested. Or is your question about whether or not the data passed in should actually be a dict or an object?

**Comment by p-galligan** [comment]
Yeah, so basically, I think the tests are structured correctly to work against a dictionary object being passed. However, the functions expect an object. So they’re not really testing the right thing, but I’m unsure on how to go about creating fake objects that I can pass into the tests.

**Comment by helrond** [comment]
Ah okay gotcha. If I am reading [this](https://github.com/archivesspace-labs/ArchivesSnake/blob/master/asnake/jsonmodel/__init__.py#L62) correctly, I think you might be able to do something like the following:
```
from asnake.jsonmodel import wrap_json_object

data = {"foo": "bar"}
object = wrap_json_object(data)
```

It looks like `wrap_json_object` calls `dispatch_type`, which looks at the data it's passed to figure out what kind of JSONModel object it is. So you'll likely need to make sure you're passing in valid data for a given AS object. I'd suggest storing stuff in files in a `fixtures` directory.

**Comment by p-galligan** [comment]
Ok, I've made some updates to this PR, but I'm still running into some errors. I generally know what's going wrong, but I'm not sure how to fix them, so a second pair of eyes from @helrond or @HaSistrunk could be useful.

FAILED tests/test_data_helpers.py::TestDataHelpers::test_get_expression - KeyError: 'expression'
One of the date objects this test is running against doesn't have an expression. Date objects without an expression don't include the expression at all, as far as I'm aware. The helper is failing because it can't find the key, but it has logic for what to do if the expression doesn't exist, which doesn't seem to be working.

FAILED tests/test_data_helpers.py::TestDataHelpers::test_text_in_note - AttributeError: 'list' object has no attribute 'strip'
The data helpers as written are trying to strip and lowercase note content. The example [here](FAILED tests/test_data_helpers.py::TestDataHelpers::test_text_in_note - AttributeError: 'list' object has no attribute 'strip') suggests that the content is a list. If I remove the list and just have a string from the single part note, it uncovers a different error.

FAILED tests/test_data_helpers.py::TestDataHelpers::test_get_note_text - AssertionError: <generator object get_note_text.<locals>.<genexpr> at 0x10cab70d0> != 'materials are restricted'
Trying to test an object against a string. Not sure how to get it to correctly test the right thing.

FAILED tests/test_data_helpers.py::TestDataHelpers::test_is_restricted - requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=4567): Max retries exceeded with url: /repositori...
Not sure what's going on with this one.

**Comment by helrond** [comment]
@p-galligan here are some responses:

>FAILED tests/test_data_helpers.py::TestDataHelpers::test_get_expression - KeyError: 'expression'

It looks like that error is actually coming from ArchivesSnake, so it might be that you need to wrap a first-class object (like an archival object or a resource) that has those dates in it, rather than trying to wrap the dates object directly.

>FAILED tests/test_data_helpers.py::TestDataHelpers::test_text_in_note - AttributeError: 'list' object has no attribute 'strip'
A couple things need to happen here:
- in `get_note_text()` the `strip` and `split` methods on note.content and note.items are both unnecessary. Lines 45-48 can look like:
```
if note.jsonmodel_type == "note_singlepart":
  content = note.content
elif note.jsonmodel_type == "note_index":
   content = note.items
```
- in `text_in_note()` we need to join the list to convert it into a string, so change line 68 to:
```
ratio = fuzz.token_sort_ratio(" ".join([n.lower() for n in note_content]), query_string.lower())
```
- last, in `test_text_in_note()` you are asserting that `result` is greater than or equal to `CONFIDENCE_RATIO`. Here, `result` is a boolean and `CONFIDENCE_RATIO` is an integer, so they will never be equal. I _think_ what you want here is:
```
self.assertTrue(result)
```

>FAILED tests/test_data_helpers.py::TestDataHelpers::test_get_note_text - AssertionError: <generator object get_note_text.. at 0x10cab70d0> != 'materials are restricted'

`get_note_text()` is a generator function, so in order to get the output you need to call `next()`, so in line 28 you need to do:
```
self.assertEqual(next(result), ["materials are restricted"])
```

You're also going to need to update the test strings because they're not matching.

>FAILED tests/test_data_helpers.py::TestDataHelpers::test_is_restricted - requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=4567): Max retries exceeded with url: /repositori...

There is a bug in `is_restricted` which was causing ArchivesSnake to attempt to make a request against ArchivesSpace, which it shouldn't have been doing. In line 243, `archival_object.rights_statement` should be `archival_object.rights_statements` (plural).

**Comment by p-galligan** [comment]
Thanks! I'll try to work on these tomorrow.

**Comment by p-galligan** [comment]
Hey, these comments were super helpful. Thank you!

I'm still failing on `FAILED tests/test_data_helpers.py::TestDataHelpers::test_get_expression - KeyError: 'expression'` even after changing the data helpers to look for an expression in an archival object. So this may be an ASnake error just in general?

Additionally, trying to figure out how to fix the is_restricted function to be able to handle the lowercase issue we were having before. `FAILED tests/test_data_helpers.py::TestDataHelpers::test_is_restricted - AttributeError: 'list' object has no attribute 'lower'`

**Comment by helrond** [comment]
@p-galligan what I was suggesting was wrapping an archival object in `test_get_expression()`, rather than just the dates. Does that work?

I'm not seeing the second error in the Travis log. I am seeing that `is_restricted()` is returning False and the test is expecting it to return True.

**Comment by p-galligan** [comment]
@helrond This is super weird. I've made updates, but the most recent travis failures don't seem to reflect them, even though they've been committed. Let me make a small change by adding comments and re-commit.

**Comment by p-galligan** [comment]
The proper errors are displaying now.

**Review by helrond — APPROVED** [review]
I don't have a problem merging this as-is, because I think it gives us a good baseline to iterate from. However, I think we will probably want to make sure we have comprehensive coverage, particularly for some of the more complex functions. I'm going to add another issue to the repository to that effect.

**Comment by p-galligan** [comment]
Yeah, I had questions about coverage on some these for sure. I could definitely use some conversation about better coverage.

**Review by HaSistrunk — APPROVED** [review]

**Pull request merged**
